from pydantic import BaseModel
from typing import Dict, Any
from datetime import datetime
import uuid

class OutputEvent(BaseModel):
    """Standard output event format generated by all models."""
    event_id: str
    user_id: str
    model_id: str
    timestamp: str
    score: float
    data: Dict[str, Any] = {}

    @classmethod
    def create(cls, user_id: str, score: float, data: Dict[str, Any] = None, model_id: str = None) -> 'OutputEvent':
        """Factory to create event with auto-generated ID/timestamp."""
        if data is None:
            data = {}
        if model_id is None:
            model_id = "unknown_model"  # overridden by model
        return cls(
            event_id=str(uuid.uuid4()),
            user_id=user_id,
            model_id=model_id,
            timestamp=datetime.now().isoformat(),
            score=score,
            data=data
        )

    def to_dict(self) -> Dict[str, Any]:
        """For serialization to Kafka (JSON)."""
        return self.model_dump() if hasattr(self, 'model_dump') else self.dict()
