// Package output defines the standard output event format generated by all models.
package output

import (
	"time"

	"github.com/google/uuid"
)

// Event is the standard output event format generated by all models.
type Event struct {
	EventID   string                 `json:"event_id"`
	UserID    string                 `json:"user_id"`
	ModelID   string                 `json:"model_id"`
	Timestamp string                 `json:"timestamp"`
	Score     float64                `json:"score"`
	Data      map[string]interface{} `json:"data"`
}

// NewEvent creates an Event with auto-generated ID and timestamp.
func NewEvent(userID string, score float64, data map[string]interface{}, modelID string) Event {
	if data == nil {
		data = make(map[string]interface{})
	}
	if modelID == "" {
		modelID = "unknown_model"
	}
	return Event{
		EventID:   uuid.New().String(),
		UserID:    userID,
		ModelID:   modelID,
		Timestamp: time.Now().Format(time.RFC3339Nano),
		Score:     score,
		Data:      data,
	}
}
